# -*- coding: utf-8 -*-
"""TTS 4 no 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRKYgSt5G0VcjzyX_zyz3yZIa2QuTSHc
"""

def hitung_panen():
    print("=== PROGRAM PENGHITUNG TOTAL HASIL PANEN ===")

    # Meminta input jumlah jenis komoditas
    try:
        jumlah_jenis = int(input("Masukkan jumlah jenis komoditas panen: "))
    except ValueError:
        print("Input harus berupa angka.")
        return

    data_panen = {}
    total_keseluruhan = 0

    # Input nama komoditas dan berat panen (dalam kg)
    for i in range(1, jumlah_jenis + 1):
        print(f"\nData ke-{i}:")
        nama = input("  Nama komoditas (misal: Padi, Jagung): ").strip().capitalize()

        while True:
            try:
                berat = float(input(f"  Jumlah hasil panen {nama} (kg): "))
                if berat < 0:
                    print("  Jumlah panen tidak boleh negatif.")
                    continue
                break
            except ValueError:
                print("  Input tidak valid. Masukkan angka.")

        data_panen[nama] = berat
        total_keseluruhan += berat

    # Menampilkan ringkasan hasil
    print("\n" + "="*40)
    print("           RINGKASAN HASIL PANEN         ")
    print("="*40)

    for komoditas, berat in data_panen.items():
        print(f"- {komoditas:<15}: {berat:>8.2f} kg")

    rata_rata = total_keseluruhan / jumlah_jenis if jumlah_jenis > 0 else 0
    terbanyak = max(data_panen, key=data_panen.get) if data_panen else "-"

    print("-" * 40)
    print(f"Total Hasil Panen  : {total_keseluruhan:.2f} kg")
    print(f"Rata-rata per Jenis: {rata_rata:.2f} kg")
    print(f"Hasil Terbanyak    : {terbanyak} ({data_panen.get(terbanyak, 0):.2f} kg)")
    print("="*40)

# Jalankan fungsi
if __name__ == "__main__":
    hitung_panen()